apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acraks
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/nareshR7420/acraks.git
    targetRevision: HEAD
    path: manifests
  destination: 
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
