apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
        env: dev
    spec:
      containers:
      - name: flask
        image: argocdacr.azurecr.io/k8sflask
        ports:
        - name:  http
          containerPort: 8080
          protocol: TCP
