name: Deploy to AKS Cluster
on: 
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
          python-version: 3.7
    - name: Install Dependencies for the app
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - uses: actions/checkout@master
    
    - uses: Azure/docker-login@v1
      with:
        login-server: argocdacr.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - run: |
        docker build . -t argocdacr.azurecr.io/k8sflask:${{ github.sha }}
        docker push argocdacr.azurecr.io/k8sflask:${{ github.sha }}
      
    # Set the target AKS cluster.
    - uses: Azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: aksdemocluster
        resource-group: aksdemo
        
    - uses: Azure/k8s-create-secret@v1
      with:
        container-registry-url: argocdacr.azurecr.io
        container-registry-username: ${{ secrets.ACR_USERNAME }}
        container-registry-password: ${{ secrets.ACR_PASSWORD }}
        secret-name: k8s-secret

    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          manifests/deployment.yaml
          manifests/service.yaml
        images: |
          argocdacr.azurecr.io/k8sflask:${{ github.sha }}
        imagepullsecrets: |
          k8s-secret
